In [1]:
import numpy as np

In [11]:
idades = np.array([10,15,20,18,20])
notas = np.array([9,8,5,7,10])

print(notas[idades==20])

[ 5 10]


In [29]:
#Média:
print(np.mean(idades))
#cos:
print(np.cos(1))
#Número infinito:
x = np.inf
print(x)

16.6
0.5403023058681398
inf


In [31]:
#Lista de segunda dimensão:
salario = np.array([[1000,1200,1300],[800,900,950],[2000,2100,2110]])

salario[1,2]

950

In [35]:
#Matriz:
matriz = np.zeros([4,3])
matriz2 = np.ones([3,2])
print(matriz)
print(matriz2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
